# Generated by Django 4.2.17 on 2026-02-20 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, help_text='Maritime Mobile Service Identity', max_length=9, unique=True)),
                ('imo', models.CharField(blank=True, db_index=True, default='', help_text='IMO number', max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('callsign', models.CharField(blank=True, default='', max_length=20)),
                ('vessel_type', models.CharField(choices=[('Cargo', 'Cargo'), ('Tanker', 'Tanker'), ('Passenger', 'Passenger'), ('Fishing', 'Fishing'), ('Tug', 'Tug'), ('Military', 'Military'), ('Sailing', 'Sailing'), ('Pleasure', 'Pleasure Craft'), ('HSC', 'High Speed Craft'), ('Pilot', 'Pilot Vessel'), ('SAR', 'Search and Rescue'), ('Other', 'Other')], db_index=True, default='Other', max_length=50)),
                ('flag', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('cargo', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed Over Ground (knots)', null=True)),
                ('course', models.FloatField(blank=True, help_text='Course Over Ground (degrees)', null=True)),
                ('heading', models.IntegerField(blank=True, help_text='True heading (degrees)', null=True)),
                ('nav_status', models.CharField(blank=True, default='', help_text='Navigation status', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('eta', models.CharField(blank=True, default='', help_text='Estimated Time of Arrival', max_length=100)),
                ('draught', models.FloatField(blank=True, help_text='Draught in meters', null=True)),
                ('length', models.FloatField(blank=True, help_text='Ship length in meters', null=True)),
                ('width', models.FloatField(blank=True, help_text='Ship width in meters', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vessel',
                'verbose_name_plural': 'Vessels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional user notes about this subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
