# Generated by Django 6.0.2 on 2026-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('congestion_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('vessel_type', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=50)),
            ],
        ),
    ]
