# Generated by Django 4.2.29 on 2026-03-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, help_text='Speed Over Ground (knots)', null=True)),
                ('course', models.FloatField(blank=True, help_text='Course Over Ground (degrees)', null=True)),
                ('heading', models.IntegerField(blank=True, help_text='True heading (degrees)', null=True)),
                ('nav_status', models.CharField(blank=True, default='', max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Vessel Position',
                'verbose_name_plural': 'Vessel Positions',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vessel', 'recorded_at'], name='vessels_ves_vessel__ee9541_idx')],
            },
        ),
    ]
