# Generated by Django 6.0.2 on 2026-02-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('congestion_score', models.FloatField()),
                ('avg_wait_time', models.FloatField()),
                ('arrivals', models.IntegerField()),
                ('departures', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vessel_type', models.CharField(max_length=50)),
                ('cargo_type', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('last_position_lat', models.FloatField()),
                ('last_position_lon', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('port_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures_from', to='core.port')),
                ('port_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals_to', to='core.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
    ]
