# Generated by Django 5.2.11 on 2026-03-04 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_notification_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('total_vessels', models.IntegerField(default=0)),
                ('total_voyages', models.IntegerField(default=0)),
                ('incidents_reported', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurerAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(max_length=100)),
                ('vessels_insured', models.IntegerField(default=0)),
                ('incidents_reported', models.IntegerField(default=0)),
                ('claims_processed', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='voyage',
            name='export_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='port',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PortAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arrivals', models.IntegerField(default=0)),
                ('total_departures', models.IntegerField(default=0)),
                ('congestion_index', models.FloatField(default=0)),
                ('avg_wait_time', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.port')),
            ],
        ),
        migrations.CreateModel(
            name='VoyageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voyage')),
            ],
        ),
    ]
